import { NextPage } from "next";
import Head from "next/head";
import LandingPageTemplate from "../templates/LandingPage/LandingPageTemplate";
import HomeComponent from "@/components/homeComponent";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>frontend</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
      <div className="bg-gray-800">
        <HomeComponent />
      </div>
    </>
  );
};

export default Index;
